# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d0547cb5bc1a10076d71641bc9474b90e1af369f6e20e3862e5fd14d35fdd5f48823c247ed73041e90906b0e6e46125b55bf2f25df8dece57b4fe5cb4b3475

test:
  secret_key_base: 378ec8c0ebc6bd9eac72dc0becfc90751748e8d875bc2f9b9ede741f5b3c20a4c6bc28b681e75f3471c52c7393b0ce14b28b03771151b8ff9abbb899a2339f47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
