# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24cd22efabaf88992978a7deda5a71e62e9b6ba5373185c8fcd90b07072e695e9f4206475afe982ab906a315781b0de1e0e0a16c58311721d6b8a9dd67c02fd

test:
  secret_key_base: 35637c34020e48cb2d94ea548582fa66b483967ecd967b26c2a565c3e555fe986270692456078d09cacebb8e55b997fedab2113afd6b44969d585cb6805ac571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
