# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78a89bdcc562eddf59be7932c021b0c416fbeb4302716c18cf26ea7a4144dd622d38426b4a70154125020a6b70d7062b77137332210db81f4f865e35003125cc

test:
  secret_key_base: a6c2c5f66dc1cc0ec117042aeb23848198fa001a1f5fa7ba14ac2808ee4f38188e70f37321bcdd72ab1d51e4b899a1aa3bf273be1a21923b59f35653dd70a2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
